Algoritmo sin_titulo
	DEFINIR A,L,A1,L1,P Como Entero
	DEFINIR OP1,OP2,OP3  Como Caracter
	ESCRIBIR "ANCHO"
	LEER A
	ESCRIBIR "LARGO"
	LEER L
	ESCRIBIR A*L
	ESCRIBIR "ANCHO1"
	LEER A1
	ESCRIBIR "LARGO1"
	LEER L1
	ESCRIBIR "PROFUNDIDAD"
	LEER P
	ESCRIBIR A1*L1
	ESCRIBIR "VOLUMEN"
	LEER V 
	ESCRIBIR "VOLUMEN1"
	LEER V1
	MOSTRAR V + V1
	MOSTRAR A*L + A1*L1 (V3*P) +1000
	
	
FinAlgoritmo
